### ISSUE TITLE
Whatsapp playground JSON builder 

### ISSUE THREAD

**Issue by mickbut-ler** [WhatsApp/WhatsApp-Flows-Tools#13]
Hi,

Could you confirm if the code for the WhatsApp Flows Playground tool is available publicly? If yes, where can I find it?

https://developers.facebook.com/docs/whatsapp/flows/playground
![Screenshot 2024-08-10 at 18 35 45](https://github.com/user-attachments/assets/beb6ec90-dbc6-4145-88d3-be201b792220)

**Comment by Gaafar** [comment]
Hi! Currently the code for the playground is not open source. Can you explain your use case to see if we can suggest an alternative?

If you want to render a preview for a specific flow, you can use the preview API which will return a URL for a web page to  preview your flow. You can also embed the preview in your own website as an iframe

https://developers.facebook.com/docs/whatsapp/flows/reference/flowsapi#preview

**Comment by mickbut-ler** [comment]
Thanks, @Gaafar.

 I want my customers to create flows using a simple UI that I can then convert into a JSON format. Am I right in understanding that the preview tool is only for flows that have already been submitted?

**Comment by Gaafar** [comment]
Correct, the preview API works with an already created flow. 

Could you direct your customers to the playground page to build the JSON and then go back to your website? Would that add too much friction? Would you prefer to keep the whole flow on your website?

**Comment by mickbut-ler** [comment]
I would prefer to keep the users on my website. Is there a possibility that the code will become available?

**Comment by Gaafar** [comment]
Understood. I will raise it with the concerned team. Would an iframe be a viable solution for you to embed the playground on your site?

**Comment by mickbut-ler** [comment]
I'll need to conduct some additional research to determine if it's feasible to share the JSON created by the customer within the iframe and integrate it with my application. Do you happen to know if this is possible?

**Comment by Gaafar** [comment]
In case we provide an iframe to embed the playground (which is not planned at the moment), it will probably share the JSON with the parent window via the postMessage API https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by mickbut-ler** [comment]
Thanks a lot @Gaafar, could you update this issue when and if this will happen?

**Comment by Gaafar** [comment]
It's not part of our plan at the moment, will update here if this changes
