### ISSUE TITLE
How can i render or display a website on whatsapp flows. 

### ISSUE THREAD

**Issue by lokii2024** [WhatsApp/WhatsApp-Flows-Tools#14]
@Gaafar 
1. Is there any way, can i display/render an website on whatsapp flows
2. meta has services of catalogue, can we display catalogue on whatsapp flows 

For ex :- Booking a ticket, on screen 1 it display the source and destination route, screen 2 ask for time, based upon that it dislay the website on whatsapp web, it won't redirect to chrome or any external browsers

![ca7340bc-0638-45b2-ad51-f9ff6d56d738](https://github.com/user-attachments/assets/4f61514f-a02f-45f8-ad02-e873e868792a)

Sorry for long image

**Comment by yehuda-lev** [comment]
It's Flows?

**Comment by yehuda-lev** [comment]
interesting, So how to do it? @Gaafar

**Comment by Gaafar** [comment]
Hi @lokii2024 & @yehuda-lev,

1. Displaying a website in Flows is currently being tested with specific partners only. Unfortunately, there is no way to request access to this feature at the moment.
2. Meta catalog integration with Flows is currently not supported.

Keep an eye on our changelog page to learn about new features as they are released https://developers.facebook.com/docs/whatsapp/flows/changelogs

**Comment by satyamupadhaya** [comment]
Is it released now? can someone please help here.

**Comment by larsblumberg** [comment]
@Gaafar Having general access to embedded webviews would allow us Flows developer creating much better user experiences and thereby increasing adaptation of Flows significantly. I don't know which influence you have over these decisions, but it would be very welcome from us Flows developers to see WebView support coming.

I had posted a request to the Facebook Developer forum here a few days ago: https://developers.facebook.com/community/threads/1078598260606281/ where I lay out 2 different ways of WebView support.

Another Flows developer made a similar request one day ago here: https://developers.facebook.com/community/threads/1222948782329484/

Alternatively if there's a way to sign up for early WebView access, as some developers seem to have access already, I am very curious to learn more about this possibility.

**Comment by jesseasamoa** [comment]
> is you have whatsapp, you can try this whatsapp buisness number (INDIA NUMBER) :- +91 890425077, you will get idea of it. Red bus whatsapp number, booking bus seats.

Number isn't on whatsapp

**Comment by yehuda-lev** [comment]
> There is no timeline or beta access for this feature at the moment, sorry.

Today I saw at the Meta conference that it was supposed to be coming soon.
![20250701_182715.jpg](https://github.com/user-attachments/assets/23fe7447-4398-4880-9474-58f2e836a4cf)

![20250701_182530.jpg](https://github.com/user-attachments/assets/e3f9f6dd-61b7-4982-9388-e9cc4111a116)

![20250701_182535.jpg](https://github.com/user-attachments/assets/525f0227-154a-4ff2-8020-ba1c1e2c7e3c)

**Comment by Gaafar** [comment]
Yes, this webview feature coming soon is not related to flows

**Comment by yehuda-lev** [comment]
> Hi, I built a tool called FLO (https://flo.wame.id/) to handle WhatsApp Flow schema generation. You just design the UI visually, and it automatically spits out production-ready code.

Wow, this is amazing!
