### ISSUE TITLE
Can we include image in Form?

### ISSUE THREAD

**Issue by lokii2024** [WhatsApp/WhatsApp-Flows-Tools#15]
1. want to pass dynamic image from the backend or can i include an image in form section, is it possible?

**Comment by Gaafar** [comment]
Yes, you can use the image component as documented here https://developers.facebook.com/docs/whatsapp/flows/reference/components#img

To make the image dynamic, you can return the base64 string from your endpoint and bind it to the image component

**Comment by lokii2024** [comment]
can i get an example for dynamic image, or in data model, from backend/endpint i have to pass image src (base64) and populate, that on layout right?
 Can i include images between the radiobuttons, instead of text, currenlty that isn't possible in flows right?
