### ISSUE TITLE
Error with Base64 Encoded Images(v5.0)

### ISSUE THREAD

**Issue by mickbut-ler** [WhatsApp/WhatsApp-Flows-Tools#16]
I’m using WhatsApp JSON Flow Builder (v5.0) and have an issue with base64 encoded images in my data model. The relevant part of my model looks like this:

```
"order_items": {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "title": {"type": "string"},
            "description": {"type": "string"},
            "image": {"type": "string"}
        }
    }
}

```

When I reference ${data.order_items} in a form, I get this error:
Expected ‘screens[1].data.order_items.items.properties.image’ to be of type ‘’.

What should the type for the image field be to handle base64 encoded images properly?

**Comment by diegolacarta** [comment]
Replied in https://developers.facebook.com/community/threads/437733759294962/
