### ISSUE TITLE
Set up flow endpoint 

### ISSUE THREAD

**Issue by mickbut-ler** [WhatsApp/WhatsApp-Flows-Tools#17]
Hi - Where is the Set up button? 
<img width="199" alt="Screenshot 2024-10-09 at 14 03 22" src="https://github.com/user-attachments/assets/b568efad-29a8-4762-b3ba-5180ce0c0983">

**Comment by Gaafar** [comment]
Endpoint setup has moved to the bottom below the code editor

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/46c7afe0-ff12-4c3d-be53-17bc9901a4db">
