### ISSUE TITLE
Support for Public Image URLs in Array Field 

### ISSUE THREAD

**Issue by mickbut-ler** [WhatsApp/WhatsApp-Flows-Tools#18]
Hi - Currently, the image field in the Array structure, for RadioButtonGroup and CheckboxGroup only supports Base64 images. We’ve encountered performance issues when using it for long lists (e.g., radio item options) because converting images to Base64 adds significant overhead, which could lead in a timeout since the api is expecting a response. 

Would it be possible to allow public image URLs as an alternative? This would improve performance in cases where multiple images need to be rendered quickly.

Thanks

**Comment by Gaafar** [comment]
Supporting image URLs is not planned at the moment.

To avoid timeouts, can you try to convert multiple images to base64 in parallel? or pregenerate/precache the base64 strings if you have a fixed list of images, instead of converting them on every request?
