### ISSUE TITLE
APPSECRET

### ISSUE THREAD

**Issue by sandyrenu** [WhatsApp/WhatsApp-Flows-Tools#2]
If the APP_SECRET is not configured, authentication should not be allowed, but currently, the request is being accepted even in this case.

**Comment by sandyrenu** [comment]
can you please provide access to my profile so that I can contribute to it.

**Comment by ankurmalik04** [comment]
Hey,

> If the APP_SECRET is not configured, authentication should not be allowed, but currently, the request is being accepted even in this case.

Thanks for raising this but this project is meant to be an example for prototyping only. It's not production ready.



> can you please provide access to my profile so that I can contribute to it.

Thanks for your interests but we are not accepting contributions on this repo right now.

Thanks
