### ISSUE TITLE
Error: Request Signature did not match

### ISSUE THREAD

**Issue by yemialpha** [WhatsApp/WhatsApp-Flows-Tools#4]
where am i getting the APP_SECRET from

**Comment by ankurmalik04** [comment]
For details about APP secret refer to https://developers.facebook.com/docs/development/create-an-app/app-dashboard/basic-settings/#app-secret

You can get your app secret and use that in the server to validate the payload https://developers.facebook.com/docs/whatsapp/flows/guides/implementingyourflowendpoint#validate-payloads

PLEASE NOTE: Never use the private keys for your production accounts outside the system. We advise to create temporary keys for testing purposes.
